export const typeListIcon = {
    "normal": "./img/icon_normal.png",
    "fire": "./img/icon_fire.png",
    "water": "./img/icon_water.png",
    "electric": "./img/icon_eletric.png",
    "grass": "./img/icon_leaf.png",
    "ice": "./img/icon_ice.png",
    "fighting": "./img/icon_punho.png",
    "poison": "./img/icon_cranio.png",
    "ground": "./img/icon_montanha.png",
    "flying": "./img/icon_vento.png",
    "psychic": "./img/icon_olho.png",
    "bug": "./img/icon_inseto.png",
    "rock": "./img/icon_cristal.png",
    "ghost": "./img/icon_fantasma.png",
    "dragon": "./img/icon_estrela.png",
    "dark": "./img/icon_lua.png",
    "steel": "./img/icon_escudo.png",
    "fairy": "./img/icon_coracao.png",
}

export const typeListColor = {
    "normal": "#A8A77A",
    "fire": "#EE8130",
    "water": "#6390F0",
    "electric": "#F7D02C",
    "grass": "#7AC74C",
    "ice": "#96D9D6",
    "fighting": "#C22E28",
    "poison": "#A33EA1",
    "ground": "#E2BF65",
    "flying": "#A98FF3",
    "psychic": "#F95587",
    "bug": "#A6B91A",
    "rock": "#B6A136",
    "ghost": "#735797",
    "dragon": "#6F35FC",
    "dark": "#705746",
    "steel": "#B7B7CE",
    "fairy": "#D685AD",
}

export const typeListColorBack = {
    "normal": "#a8a77a80",
    "fire": "#ee82307a",
    "water": "#6390f071",
    "electric": "#f7ce2c70",
    "grass": "#79c74c6b",
    "ice": "#96d9d670",
    "fighting": "#c22d2875",
    "poison": "#a33ea170",
    "ground": "#e2bf656e",
    "flying": "#aa8ff37a",
    "psychic": "#f9558671",
    "bug": "#a6b91a75",
    "rock": "#b6a1367e",
    "ghost": "#7357976b",
    "dragon": "#6d35fc77",
    "dark": "#7057467e",
    "steel": "#b7b7ce6e",
    "fairy": "#d685ad75",
}